#!/usr/bin/env python3

# https://colors.eva.design/
# https://onlinepngtools.com/change-png-color
# COLORS
# Battery
###############################
PROGRESSCOLOR = "#4BD680" # --green used
BACKPROGRESSCOLOR = '#7C7C79' # --used
YELLOWBATTERY = '#E4AC3A' # --used
REDBATTERY = '#FF6F79' # --used
####################################

ORANGE = '#e69138'
BLUE = '#007A96'#"#018DBE" --used
LIGHTBLUE = '#3294ab'
DARKBLUE = '#006178'
SEGMENTEDPRESSED = "#B56C01"  #ORANGE
LIGHTORANGE = '#c38933'
DARKORANGE = '#905600'

FG_DATABUTTON_COLOR = '#121279' #070740' -> used
HOVER_DATABUTTON_COLOR = '#3939D1'#191970' -> used
FG_SETPOINTBUTTON_COLOR = '#055F4A' #
HOVER_SETPOINTBUTTON_COLOR = '#12A557' #
FG_ERRORBUTTON_COLOR = '#8A0B2C' #
HOVER_ERRORBUTTON_COLOR = '#EF2323' #
FG_OUTBUTTON_COLOR = '#014493' #
HOVER_OUTBUTTON_COLOR = '#05A7FF' #
FG_CREATIONBUTTON_COLOR = '#FC8607' #
HOVER_CREATIONBUTTON_COLOR = '#B54E03' #
FG_ACTIVATEBUTTON_COLOR = '#2c6a5e'
HOVER_ACTIVATEBUTTON_COLOR = "#49b29e"

#graph
WHITE = '#E1E1E1' # --used in graph --white color in the graph
GRAPHBLUE = '#3939D1' # --used graph --variable
GRAPHGREEN = '#208728' # --used graph --setpoint
GRAPHRED = '#8E1927' # --used graph --error
GRAPHLIGHTBLUE = '#008789' # --used graph --system output
###########################################

HOVERFINISHBUTTONS = '#9B5600' # --used
DARKGRAY = "#1A1A12" #'#2c2c2c' # --used
GRAY = "#1F1F1A"  # --used

# GENERAL DRONE PARAMETERS 
DEFAULT_SPEED = 50
PROGRESSDEFAULT = 0.9 # Used in battery
DEFAULTCONFIGURATION = "SLAVE" # It can be slave or master
STARTDEFAULTCONFIGURATION = False
KEYBOARDEVENTS = True

# THROTTLE PARAMETERS TRANSLATIONAL UP/DOWN MOVEMENT
# master
# Z AXIS
MAX_OUTPUT_THROTTLE = 60
MIN_OUTPUT_THROTTLE = -60
DEFAULT_THROTTLE = 50 # DELETE LATER (MAYBE)
DEFAULT_PROPORTIONAL_VALUE_THROTTLE = 1.6
DEFAULT_INTEGRAL_VALUE_THROTTLE = 0.6 
DEFAULT_DERIVATIVE_VALUE_THROTTLE = 0.4 
#slave
# Z AXIS
MAX_OUTPUT_THROTTLE_MASTER = 60
MIN_OUTPUT_THROTTLE_MASTER = -60
DEFAULT_THROTTLE_MASTER = 50
DEFAULT_PROPORTIONAL_VALUE_THROTTLE_MASTER = 1.6
DEFAULT_INTEGRAL_VALUE_THROTTLE_MASTER = 0.6
DEFAULT_DERIVATIVE_VALUE_THROTTLE_MASTER = 0.4

# YAW PARAMETERS ROTATIONAL TURN LEFT/RIGHT(SPIN)
# Z AXIS
MAX_OUTPUT_YAW = 0
MIN_OUTPUT_YAW = 0
DEFAULT_YAW = 0 # DELETE LATER (MAYBE)
DEFAULT_PROPORTIONAL_VALUE_YAW = 0.0
DEFAULT_INTEGRAL_VALUE_YAW = 0.0
DEFAULT_DERIVATIVE_VALUE_YAW = 0.0

# ROLL PARAMETERS TRANSLATIONAL LEFT/RIGHT TILT
# X-AXIS
MAX_OUTPUT_ROLL = 0
MIN_OUTPUT_ROLL = 0
DEFAULT_ROLL = 0 # DELETE LATER (MAYBE)
DEFAULT_PROPORTIONAL_VALUE_ROLL = 0.0
DEFAULT_INTEGRAL_VALUE_ROLL = 0.0
DEFAULT_DERIVATIVE_VALUE_ROLL = 0.0

# PITCH PARAMETERS TRANSLATIONAL FORWARD/BACKWARD TILT
# Y-AXIS
MAX_OUTPUT_PITCH = 0
MIN_OUTPUT_PITCH = 0
DEFAULT_PITCH = 0 # DELETE LATER (MAYBE)
DEFAULT_PROPORTIONAL_VALUE_PITCH = 0.0
DEFAULT_INTEGRAL_VALUE_PITCH = 0.0
DEFAULT_DERIVATIVE_VALUE_PITCH = 0.0
